<a href="https://colab.research.google.com/github/arifnayan2861/DA/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# series

In [ ]:
#creating series from list
data = [1,2,3,4,5]
series = pd.Series(data)
print(series, type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'>

In [ ]:
#creating series from dictionary
data2 = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
series2 = pd.Series(data2)
print(series2, type(series2))

a    1
b    2
c    3
d    4
e    5
dtype: int64 <class 'pandas.core.series.Series'>

In [ ]:
data3 = ['a', 'b', 'c']
series3 = pd.Series(data3, index=[1,2,3])
print(series3, type(series3))

1    a
2    b
3    c
dtype: object <class 'pandas.core.series.Series'>

# dataframes

In [ ]:
data = {
    'Name': ['John', 'Jane', 'Jack', 'Jill'],
    'Age': [25, 30, 35, 40],
}
df = pd.DataFrame(data)
print(df, type(df))

   Name  Age
0  John   25
1  Jane   30
2  Jack   35
3  Jill   40 <class 'pandas.core.frame.DataFrame'>

In [ ]:
data = [
    {"name": "john", "age": 25},
    {"name": "jane", "age":30},
    {"name": "jack", "age": 35},
    {"name": "jill", "age": 40}
]
df = pd.DataFrame(data)
print(df)

   name  age
0  john   25
1  jane   30
2  jack   35
3  jill   40

In [ ]:
data = [
    ["john",25], ["jane", 30], ["jack", 35], ["jill", 40]
]
df = pd.DataFrame(data, columns=["name", "age"])
print(df)

   name  age
0  john   25
1  jane   30
2  jack   35
3  jill   40

reading data from csv file

In [ ]:
df = pd.read_csv("/content/02. data.csv")
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
df["Value"][0]

28.0

In [ ]:
df["Region"].head()

0     East
1    North
2     East
3     East
4    North
Name: Region, dtype: object

In [ ]:
print(df.index)
print(df.columns)
print(df.shape)
df.info()

RangeIndex(start=0, stop=50, step=1)
Index(['Date', 'Category', 'Value', 'Product', 'Sales', 'Region'], dtype='object')
(50, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     object
 1   Category  50 non-null     object
 2   Value     47 non-null     float64
 3   Product   50 non-null     object
 4   Sales     46 non-null     float64
 5   Region    50 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.5+ KB

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [ ]:
#column selection single
df["Region"].head()

0     East
1    North
2     East
3     East
4    North
Name: Region, dtype: object

In [ ]:
#column selection multiple
df[["Region", "Value"]].head()

  Region  Value
0   East   28.0
1  North   39.0
2   East   32.0
3   East    8.0
4  North   26.0

In [ ]:
#row selection
df.iloc[0]

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [ ]:
#row selection with condition(multiple)
df.loc[df["Value"] < 30]

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
6   2023-01-07        A   16.0  Product1  936.0   East
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
24  2023-01-25        A   24.0  Product2  458.0   East
31  2023-02-01        A   17.0  Product2  189.0   West
33  2023-02-03        C   27.0  Product3    NaN   East
37  2023-02-07        C    2.0  Product1    NaN  North
40  2023-02-10        B   15.0  Product1  578.0   East
46  2023-02-16        B    6.0  Product1  938.0  South
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.loc[df["Value"] < 30, ["Region", "Value"]]

   Region  Value
0    East   28.0
3    East    8.0
4   North   26.0
6    East   16.0
9    West   22.0
10  North    7.0
24   East   24.0
31   West   17.0
33   East   27.0
37  North    2.0
40   East   15.0
46  South    6.0
49  North   11.0

In [ ]:
df.loc[df["Value"] == 32]

         Date Category  Value   Product  Sales Region
2  2023-01-03        C   32.0  Product2  398.0   East

In [ ]:
df.iloc[0, 1]

'A'

In [ ]:
#adding new column
df["Sales per Month"] = df["Sales"] * 30
df.head()

         Date Category  Value   Product  Sales Region  Sales per Month
0  2023-01-01        A   28.0  Product1  754.0   East          22620.0
1  2023-01-02        B   39.0  Product3  110.0  North           3300.0
2  2023-01-03        C   32.0  Product2  398.0   East          11940.0
3  2023-01-04        B    8.0  Product1  522.0   East          15660.0
4  2023-01-05        B   26.0  Product3  869.0  North          26070.0

In [ ]:
#grouping & aggregation
grouped = df.groupby("Region")["Sales"].mean()
print(grouped)

Region
East     584.7500
North    600.8000
South    644.7500
West     465.3125
Name: Sales, dtype: float64

In [2]:
df = pd.read_csv("/content/02. data.csv")
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [3]:
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [4]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [5]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [6]:
#handling missing values
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [7]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [9]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [10]:
df.fillna(0)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [11]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [13]:
df["Sales_fillNA"] = df["Sales"].fillna(df["Sales"].mean())
df

          Date Category  Value   Product  Sales Region  Sales_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [14]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [18]:
#renaming columns
df=df.rename(columns={"Date": "Sales Date"})
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [21]:
#change data types
df["Value_int"] = df["Value"].fillna(df["Value"].mean()).astype(int)
df

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_int
0,2023-01-01,A,28.0,Product1,754.0,East,754.000000,28
1,2023-01-02,B,39.0,Product3,110.0,North,110.000000,39
2,2023-01-03,C,32.0,Product2,398.0,East,398.000000,32
3,2023-01-04,B,8.0,Product1,522.0,East,522.000000,8
4,2023-01-05,B,26.0,Product3,869.0,North,869.000000,26
5,2023-01-06,B,54.0,Product3,192.0,West,192.000000,54
6,2023-01-07,A,16.0,Product1,936.0,East,936.000000,16
7,2023-01-08,C,89.0,Product1,488.0,West,488.000000,89
8,2023-01-09,C,37.0,Product3,772.0,West,772.000000,37
9,2023-01-10,A,22.0,Product2,834.0,West,834.000000,22
10,2023-01-11,B,7.0,Product1,842.0,North,842.000000,7
11,2023-01-12,B,60.0,Product2,NaN,West,557.130435,60
12,2023-01-13,A,70.0,Product3,628.0,South,628.000000,70
13,2023-01-14,A,69.0,Product1,423.0,East,423.000000,69
14,2023-01-15,A,47.0,Product2,893.0,West,893.000000,47
15,2023-01-16,C,NaN,Product1,895.0,North,895.000000,51
16,2023-01-17,C,93.0,Product2,511.0,South,511.000000,93
17,2023-01-18,C,NaN,Product1,108.0,West,108.000000,51
18,2023-01-19,A,31.0,Product2,578.0,West,578.000000,31
19,2023-01-20,A,59.0,Product1,736.0,East,736.000000,59
20,2023-01-21,C,82.0,Product3,606.0,South,606.000000,82
21,2023-01-22,C,37.0,Product2,992.0,South,992.000000,37
22,2023-01-23,B,62.0,Product3,942.0,North,942.000000,62
23,2023-01-24,C,92.0,Product2,342.0,West,342.000000,92
24,2023-01-25,A,24.0,Product2,458.0,East,458.000000,24
25,2023-01-26,C,95.0,Product1,584.0,West,584.000000,95
26,2023-01-27,C,71.0,Product2,619.0,North,619.000000,71
27,2023-01-28,C,56.0,Product2,224.0,North,224.000000,56
28,2023-01-29,B,NaN,Product3,617.0,North,617.000000,51
29,2023-01-30,C,51.0,Product2,737.0,South,737.000000,51
30,2023-01-31,B,50.0,Product3,735.0,West,735.000000,50
31,2023-02-01,A,17.0,Product2,189.0,West,189.000000,17
32,2023-02-02,B,63.0,Product3,338.0,South,338.000000,63
33,2023-02-03,C,27.0,Product3,NaN,East,557.130435,27
34,2023-02-04,C,70.0,Product3,669.0,West,669.000000,70
35,2023-02-05,B,60.0,Product2,NaN,West,557.130435,60
36,2023-02-06,C,36.0,Product3,177.0,East,177.000000,36
37,2023-02-07,C,2.0,Product1,NaN,North,557.130435,2
38,2023-02-08,C,94.0,Product1,408.0,South,408.000000,94
39,2023-02-09,A,62.0,Product1,155.0,West,155.000000,62
40,2023-02-10,B,15.0,Product1,578.0,East,578.000000,15
41,2023-02-11,C,97.0,Product1,256.0,East,256.000000,97
42,2023-02-12,A,93.0,Product3,164.0,West,164.000000,93
43,2023-02-13,A,43.0,Product3,949.0,East,949.000000,43
44,2023-02-14,A,96.0,Product3,830.0,East,830.000000,96
45,2023-02-15,B,99.0,Product2,599.0,West,599.000000,99
46,2023-02-16,B,6.0,Product1,938.0,South,938.000000,6
47,2023-02-17,B,69.0,Product3,143.0,West,143.000000,69
48,2023-02-18,C,65.0,Product3,182.0,North,182.000000,65
49,2023-02-19,C,11.0,Product3,708.0,North,708.000000,11

In [26]:
df["New Value"] = df["Value_int"].apply(lambda x : x * 2)
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_int,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52

In [27]:
#data aggregating & grouping
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_int,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52

In [30]:
grouped_mean = df.groupby("Product")['Value_int'].mean()
grouped_mean

Product
Product1    46.812500
Product2    52.800000
Product3    54.947368
Name: Value_int, dtype: float64

In [31]:
df.groupby("Product")['Value_int'].agg(['mean', 'sum', 'count'])

               mean   sum  count
Product
Product1  46.812500   749     16
Product2  52.800000   792     15
Product3  54.947368  1044     19

In [33]:
df.groupby(["Product", "Region"])["Value_int"].agg(['count', 'sum', 'mean'])

                 count  sum       mean
Product  Region
Product1 East        7  292  41.714286
         North       3   60  20.000000
         South       2  100  50.000000
         West        4  297  74.250000
Product2 East        2   56  28.000000
         North       2  127  63.500000
         South       3  181  60.333333
         West        8  428  53.500000
Product3 East        4  202  50.500000
         North       6  254  42.333333
         South       3  215  71.666667
         West        6  373  62.166667

In [35]:
df.groupby(["Region", "Product", "Category"])["Value_int"].agg(['count', 'sum', 'mean'])

                          count  sum       mean
Region Product  Category
East   Product1 A             4  172  43.000000
                B             2   23  11.500000
                C             1   97  97.000000
       Product2 A             1   24  24.000000
                C             1   32  32.000000
       Product3 A             2  139  69.500000
                C             2   63  31.500000
North  Product1 B             1    7   7.000000
                C             2   53  26.500000
       Product2 C             2  127  63.500000
       Product3 B             4  178  44.500000
                C             2   76  38.000000
South  Product1 B             1    6   6.000000
                C             1   94  94.000000
       Product2 C             3  181  60.333333
       Product3 A             1   70  70.000000
                B             1   63  63.000000
                C             1   82  82.000000
West   Product1 A             1   62  62.000000
                C             3  235  78.333333
       Product2 A             4  117  29.250000
                B             3  219  73.000000
                C             1   92  92.000000
       Product3 A             1   93  93.000000
                B             3  173  57.666667
                C             2  107  53.500000